linters:
  enable:
    - gofumpt
    - revive

linters-settings:
    rewrite-rules:
      - pattern: interface{}
        replacement: any
    revive:
      rules:
        - name: use-any

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  formats: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true
