[tool.poetry]
name = "python"
version = "0.1.0"
description = ""
authors = ["Jojo <jonathan.silva@birdie.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic-factories = "^1.17.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
