name: service1 CI

on:
  push:
    paths:
      - 'python/services-example/**'
  pull_request:
    paths:
      - 'python/services-example/**'

jobs:
  determine-service:
    runs-on: ubuntu-latest
    outputs:
      service: ${{ steps.set-services.outputs.services }}
    steps:
      - uses: actions/checkout@v4
      - id: set-services
        run: |
          SERVICES=$(ls -d python/services-example/service* | jq -R -s -c 'split("\n")[:-1]')
          echo "services=$SERVICES" >> $GITHUB_OUTPUT

  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-root

      - name: lint-format-test
        run: |
          make lint
          make fmt
          make test
